#

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "ras-connections"
    static_configs:
      - targets: ["10.61.36.106:9182"]